public class ARV_AP_BRInfoWrapperclasses {
    public class MedicalAttributeWrapper{
        public string CompMedicalRatingForm;
        public string CompDrugForms;
        public string CompMedicalForms;
        public string RegularDrugForms;
        public string RegularMedicalForms;
        public String RegularStandardMedicalForms;
        public String RegularStandardDrugForms;
        public String CompHIOSID2;
    }
    public class DentalAttributeWrapper{
        public string CompDentalForms;
        public string RegularDentalForms;   
    }
    public class VisionAttributeWrapper{
         public String CompVisionForms;
         public String RegularVisionForms;      
    }

}