/*****************************************************************************************
Class Name   : ARV_AP41_StringLiteralUtils
Date Created : 28-July-2019
Created By   : IDC Offshore
Description  :This is to maintain the String Literals using across all the classes.
*******************************************************************************/
public with sharing class ARV_AP41_StringLiteralUtils
{
    public static final string TYPEINSERT='insert';
    public static final string TYPEUPDATE='update';
    public static final string TYPEADD ='add';
    public static final string TYPEDELETE='delete';
    public static final string TYPEUPSERT='upsert';
    public static final string TYPEOPEN='open';
    public static final string SBCTYPE='SBC';
    public static final string BAAGTYPE='BAAG';
    public static final string BCBSTYPE='BCBS';
    public static final string BCNTYPE='BCN';
    public static final string SEPERATEDVAL='-';
    public static final string SEPERATOR=';';
    public static final string QUOID='quoteId';
    public static final string MYBLANKVAL='';
    public static final string MEDICALTYPE='Medical';
    public static final string DENTALTYPE='Dental';
    public static final string VISIONTYPE='Vision';
    public static final string RATEGRID='RateGrid';
    public static final string COVERPAGE='CoverPage';
    public static final string CAARIERTYPE='carrierType';
    public static final Boolean TRUE_VALUE= true;
    public static final Boolean FALSE_VALUE = false;
    public static final String NULLSTRING = null;
    public static final String SLASH = '/';
    public static final string CENSUSVAL='Census';
    public static final string CONTENTTYPE='application/pdf';
    public static final String  COMMAVAL = ','; 
    public static final String  COLONVAL = ':';
    public static final String  HYPHENVAL = '-';
    public static final String  SPACEVAL =' ';
    public static final string ACCOUNTCUSTOMER='Account_Customer';
    public static  final string ACCOUNTPROSPECT= 'Account_Prospect';
    public static final string ACCOUNTINACTIVE='Account_Inactive';
    Public static final string UNQUALIFIEDPROSPECT='Unqualified_Prospect_Agent';
    Public static final string YESVAL='yes';
    Public static final string NOVAL='no';
    Public static final String  VOLUNTARY='Voluntary';
    Public static final String  NONVOLUNTARY='Non-Voluntary';
    Public static final String  NOTOFFERED='Not Offered';
    Public static final String  HBAVAL = 'Healthy Blue Living';
    Public static final String  HBACH= 'Healthy Blue Achieve';
    Public static final String  HSA='BCN HSA';
    public static final String BCBSMVAL='BCBSM';
    public static final String REDYFORINTGRTN = 'Ready for Integration';
    public static final String MANUL = 'Manual';
    public static final String OPNLBL='Open';
    public static final String EMPTYSTRNG='';
    public static final String ENHANCED='Enhanced';
    public static final String STANDARD='Standard';
    
    public static final string PACKUPD='Update';
    public static final string PACKADD ='Add'; 
    public static final string SUBMITTED='Submitted';
    public static final string INPROGRESS='In Progress';
    public static final string UNDERREVIEW='Under Review';
    
    public static final string NEWDENTALPLAN='New Dental Plan:';
    public static final string NEWVISIONPLAN='New Vision Plan:';
    public static final string OLDDENTALPLAN='Old Dental Plan:';
    public static final string OLDVISIONPLAN='Old Vision Plan:';
    public static final string NEWDENTALTYPE='New Dental Type:';
    public static final string OLDDENTALTYPE='Old Dental Type:';
    public static final string NEWDENTALPRODCODE='New Dental Product Code:';
    public static final string OLDDENTALPRODCODE='Old Dental Product Code:';
    public static final string NEWMEDICALPRODCODE='New Medical Product Code:';
    public static final string OLDMEDICALPRODCODE='Old Medical Product Code:';
    public static final string NEWVISIONTYPE='New Vision Type:';
    public static final string OLDVISIONTYPE='Old Vision Type:';
    public static final string NEWVISIONPRODCODE='New Vision Product Code:';
    public static final string OLDVISIONPRODCODE='Old Vision Product Code:';
    public static final string NEWCARRIER='New Carrier:';
    public static final string OLDCARRIER='Old Carrier:';
    public static final string OLDPRODUCTFAMILY='Old Product Family:';
    public static final string NEWPRODUCTFAMILY='New Product Family:';
    public static final string OLDMEDICALPLAN='Old Medical Plan:';
    public static final string NEWMEDICALPLAN='New Medical Plan:';
    public static final string NEWCDHPLAN ='New CDH Package Combination:';
    public static final string OLDCDHPLAN='Old CDH Package Combination:';
    
    public static final String GSGWCCMP='Group Segment Setup Complete';
    public static final string MNLGWCRDY='Manual GWC Setup – Ready';
    public static final string AUTGWCRDY='Automated GWC Setup - Integration Ready';
    public static final string MNLGWCPRC='Manual GWC Setup – Processing';
    public static final string EXBNPKGNC= 'Existing Benefit Package No Change';
    public static final string RATINGAREAUPD='Rating Area Update';
    public static final String RATARMODBENPKG='Rating Area with Modify Benefit Package';
    public static final String RATINGAREA='Rating Area';
    
    public static final String MODIFYPACKAGE='Modify Benefit Package';
    public static final String ADDPACKAGE='Add Benefit Package';
    public static final String ADDLOCATION='Add Location';
    
    public static final string NOCDH='No CDH';
    public static final string NOTAVAILABLE='N/A';
 

}